name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
    - sandbox/PerfBenchmark/**
  release:
    types: [ published ]    

defaults:
  run:
    working-directory: sandbox/PerfBenchmark

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Benchmark
      run: dotnet run --configuration Release -f net6.0 --filter '*' --runOncePerIteration
